"""Generate ``src/ifsplit/_recipes.py`` from the ``config/*.yaml`` recipes.

The installed wheel packages only ``src/ifsplit`` (see ``pyproject.toml``), so the
``config/`` recipes are NOT shipped. ``if-split init`` still needs them to scaffold
a config, so their text is embedded verbatim in ``_recipes.py``. This script keeps
that copy byte-identical to the source-of-truth files; ``test_wizard`` guards drift.

Regenerate after editing any ``config/*.yaml``:

    uv run python scripts/gen_recipes.py
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "ifsplit" / "_recipes.py"

# recipe name -> source YAML (the wizard's --recipe choices).
RECIPES = {
    "default": ROOT / "config" / "default.yaml",
    "fold-aware": ROOT / "config" / "fold-aware.yaml",
}

HEADER = '''"""Embedded copies of the ``config/*.yaml`` recipes (for ``if-split init``).

GENERATED by ``scripts/gen_recipes.py`` — do not edit by hand. The wheel omits
``config/``, so these literals are the wizard's only source for the base recipes.
Regenerate when a recipe changes; ``tests/test_wizard.py`` fails on drift.
"""

from __future__ import annotations
'''


def _literal(name: str, text: str) -> str:
    # A triple-quoted literal reproduces the YAML byte-for-byte only when it holds
    # no ''' and no backslash escapes; the recipes never do. If that ever changes,
    # fail loudly here rather than silently corrupt the embedded copy.
    if "'''" in text:
        raise ValueError(f"{name}: recipe contains ''' — cannot embed as a triple-quoted literal")
    if "\\" in text:
        raise ValueError(f"{name}: recipe contains a backslash — triple-quoted embedding unsafe")
    if not text.endswith("\n") or text.endswith("'"):
        raise ValueError(
            f"{name}: recipe must end with a newline (and not a quote) to embed safely"
        )
    return f"{name} = '''{text}'''\n"


def main() -> int:
    const_names = {"default": "RECIPE_DEFAULT", "fold-aware": "RECIPE_FOLD_AWARE"}
    parts = [HEADER]
    entries = []
    for name, path in RECIPES.items():
        text = path.read_text(encoding="utf-8")
        parts.append("\n" + _literal(const_names[name], text))
        entries.append(f'    "{name}": {const_names[name]},')
    parts.append("\n# recipe name (an ``if-split init --recipe`` choice) -> embedded YAML text.\n")
    parts.append("RECIPES: dict[str, str] = {\n" + "\n".join(entries) + "\n}\n")
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(RECIPES)} recipes embedded)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
