"""Embedded copies of the ``config/*.yaml`` recipes (for ``if-split init``).

GENERATED by ``scripts/gen_recipes.py`` — do not edit by hand. The wheel omits
``config/``, so these literals are the wizard's only source for the base recipes.
Regenerate when a recipe changes; ``tests/test_wizard.py`` fails on drift.
"""

from __future__ import annotations

RECIPE_DEFAULT = '''# IF-Split run configuration — the single source of truth for a build.
#
# Every parameter here affects the output. The config is hashed (canonical,
# formatting-independent) and the hash is embedded in the manifest, so two
# manifests with the same config-hash used identical settings.

snapshot_date: "2026-05-30"        # release_date <= this. The reproducibility anchor.
experimental_methods: ["X-RAY DIFFRACTION", "ELECTRON MICROSCOPY"]
resolution_max_A: 3.5
# Optional per-method resolution overrides (a method here uses its own cap instead of
# resolution_max_A). Cryo-EM 3.5 A has far less sidechain signal than X-ray 3.5 A, so a
# tighter EM cap is common. Enforced in Stage 3 (auditable); empty = one cap for all.
# Example: {"ELECTRON MICROSCOPY": 3.0}
resolution_max_A_by_method: {}
max_total_residues: 5999           # max residues KEPT (drop if > this); LigandMPNN kept < 6000
# Opt-in sequence-usability floor: keep an entry only if some protein chain has at
# least this many modeled (non-X) residues. 0 = off (only the always-on empty/all-X
# poly-UNK drop applies). Try ~20 to also drop tiny peptide fragments / mostly-unknown
# chains whose sequence is a poor inverse-folding label.
min_modeled_residues: 0
# Opt-in single-chain filter: keep only entries with exactly one protein polymer
# entity and no other polymer (no second protein type, no nucleic acid) — a metadata
# proxy for a single-chain design target (ProteinMPNN's single-chain CATH setup). A
# homo-oligomer of one entity still passes. Off by default.
single_chain_only: false
excluded_het: ["HOH", "NA", "CL", "K", "BR"]   # waters + common crystallization ions
use_biological_assembly: true      # biounits, as in LigandMPNN (assembly 1)

# Curation: purification-artifact detection (Stage 4). A poly-His tag that
# coordinates Ni/Co is an artifact of affinity purification, not a biological
# metal site — a known blemish in the LigandMPNN metal set. An entry whose only
# metal is a purification metal AND that carries a His-tag (a >= histag_min_run
# run anywhere, OR a >= histag_terminal_min_run run at a chain terminus — to
# catch 6xHis tags left partial by unmodeled/trimmed residues) is flagged as an
# artifact. Set purification_metals: [] to disable.
#
# Even without a detectable tag, a *lone* Ni/Co with no measured affinity is
# demoted from `functional` to `ambiguous` (reported, not labelled): ~82% of lone
# Ni/Co in the PDB carry no detectable His-tag (IMAC tags are often absent from
# the deposited SEQRES), so a bare contact is weak evidence of a biological metal
# site. This re-tiers roughly 70% of the lone-Ni/Co set and does over-fire on some
# real bare-Ni/Co enzymes, which the annotate-never-drop tier keeps recoverable.
# Real metals (Zn, Mg, Fe, Mn, …) and Ni/Co alongside another real metal or with
# affinity are unaffected. See scripts/audit_nico_histag.py for the derivation.
purification_metals: ["NI", "CO"]
histag_min_run: 6
histag_terminal_min_run: 3
exclude_purification_artifacts: true

identity_threshold: 0.30           # clustering cutoff (Data API levels: 30/50/70/90/95/100)
clustering_backend: "precomputed"  # reuse RCSB's published 30% clusters (the only backend; locked via the snapshot)
# Fold-leakage control: off | cath | ecod | scop2 | pfam | interpro | union | all.
# "all" (default) merges on every authority the metadata offers. The three curated
# structural classifications are not enough on their own: they lag deposition badly
# (0.8% of pre-2020 entries unclassified vs 55.3% of 2026), so a holdout built from them
# is disjoint partly because the databases have not caught up -- measured, 75.9% of the
# entries that looked novel and carry an HMM family in fact share one with train. Pfam and
# InterPro are HMMs over sequence, so they carry no lag (InterPro alone covers 94.9% of
# entries vs 92.3% for all three structural authorities combined).
structural_clustering: "all"      # fold-leakage control: off|cath|ecod|scop2|pfam|interpro|union|all
# Novel-fold benchmark export: off | cath | ecod | scop2 (opt-in). Emits folds.json,
# fold_groups.json, novel_fold_test.json; fold labels are DECOUPLED from fold merging,
# so it never changes the split. Omitted from the config hash when off. See README.
fold_benchmark_method: "off"
split_fractions: {train: 0.80, val: 0.10, test: 0.10}
# "hash" (balance components) | "balanced" (balance entries) | "maximal" (default: derive
# the holdout SIZE from the data). Under strong merging the PDB collapses into one giant
# component, so the largest leakage-safe holdout is whatever remains -- "maximal" takes
# exactly that and splits it evenly, treating split_fractions below as a CEILING rather
# than a target. "balanced" would instead demand 10/10 and empty val when the tail is thin.
split_strategy: "maximal"          # "hash" | "balanced" | "maximal" (derive holdout from data)
split_salt: "snapsplit-v1"         # bump to reshuffle intentionally
seed: 0

# Optional test-set stratification top-up. A floor on the number of test entries
# carrying each functional ligand class. Empty = off (pure deterministic hash).
# When set, after the base split any class below its floor recruits WHOLE sequence
# components (never individual entries -> no leakage) into test, in deterministic
# hash order, skipping registry-pinned components (growth stays stable). A floor
# larger than the available supply is met as far as possible; the shortfall is
# reported in the manifest, not forced. Example: {metal: 500, nucleic_acid: 200}
test_min_per_class: {}

# Quality filters (Stage 3) — wwPDB validation-report metrics, fetched as
# metadata (NO coordinate download). Each cap is optional: null disables it. An
# entry is dropped only when the metric is present AND exceeds the cap; entries
# whose report lacks a metric are kept (never penalized for an absent metric).
# Geometry caps (clashscore/Ramachandran/rotamer) apply to BOTH X-ray and cryo-EM;
# diffraction caps (R-free/RSRZ) are X-ray-only and no-op on EM. Defaults are off
# so the snapshot is unchanged until you opt in; suggested high-quality starting
# points are shown in the trailing comments.
max_clashscore: null                 # e.g. 40    (all-atom clashes/1000 atoms; lower=better)
max_rfree: null                      # e.g. 0.30  (X-ray DCC R-free)
max_ramachandran_outlier_pct: null   # e.g. 1.0   (% backbone Ramachandran outliers)
max_rotamer_outlier_pct: null        # e.g. 5.0   (% sidechain rotamer outliers)
max_rsrz_outlier_pct: null           # e.g. 20    (% real-space-R Z-score outliers, X-ray)
min_em_backbone_inclusion: null      # e.g. 0.7   (cryo-EM map-fit FLOOR, higher=better; EM-only)
require_validation_report: false     # drop entries lacking a validation report entirely

# Ligand context (downstream-optional; featurization, not split definition).
ligand_context_radius_A: 8.0
max_ligand_atoms: 25
'''

RECIPE_FOLD_AWARE = '''# IF-Split "fold-aware" config — a fold-honest split for inverse-folding training.
#
# Same as config/default.yaml, but two settings turn on the strongest leakage
# control the tool offers:
#   structural_clustering: "scop2"  — merge same-fold chains (CATH/ECOD/SCOP2
#     classifications, metadata only) so a fold cannot straddle train/test, not
#     just a sequence cluster. scop2 is chosen for coverage + balance: on the full
#     PDB it leaves a rich enough fold tail to still balance val/test (cath/ecod
#     collapse into one dominant mega-fold and starve val — see the README).
#   split_strategy: "balanced"      — cap the dominant folds (antibodies, TIM
#     barrels) to train and fill val/test to their ENTRY targets from the tail of
#     smaller folds. Restores ~80/10/10 by entries with thousands of distinct,
#     held-out folds in val/test — a truer generalization measure.
#
# Build it:  uv run if-split build --config config/fold-aware.yaml --out data/mc
# `if-split stats` reports the fold-merge effect, the capped folds, and any gap.

snapshot_date: "2026-05-30"        # release_date <= this. The reproducibility anchor.
experimental_methods: ["X-RAY DIFFRACTION", "ELECTRON MICROSCOPY"]
resolution_max_A: 3.5
resolution_max_A_by_method: {"ELECTRON MICROSCOPY": 3.0}  # cryo-EM 3.5A != X-ray 3.5A for sidechains
max_total_residues: 5999           # max residues KEPT (drop if > this); LigandMPNN kept < 6000
min_modeled_residues: 20           # drop tiny/poly-UNK chains: the sequence is the training label
excluded_het: ["HOH", "NA", "CL", "K", "BR"]
use_biological_assembly: true

purification_metals: ["NI", "CO"]
histag_min_run: 6
histag_terminal_min_run: 3
exclude_purification_artifacts: true

identity_threshold: 0.30
clustering_backend: "precomputed"
structural_clustering: "scop2"     # fold-level leakage control (the fold-aware lever)
# fold_benchmark_method: ecod      # opt-in novel-fold sidecars (folds.json, fold_groups.json,
#                                  # novel_fold_test.json). Use a DIFFERENT authority than
#                                  # structural_clustering (scop2) above: matching them makes the
#                                  # novel-fold count a tautological ~100% (the same-method merge
#                                  # already forbids a fold from straddling splits). off (default)
#                                  # emits nothing, omitted from the config hash. Labels never
#                                  # change the split.
split_fractions: {train: 0.80, val: 0.10, test: 0.10}
split_strategy: "balanced"         # entry-balanced, fold-tail val/test
split_salt: "snapsplit-v1"
seed: 0

test_min_per_class: {}

max_clashscore: null
max_rfree: null
max_ramachandran_outlier_pct: null
max_rotamer_outlier_pct: null
max_rsrz_outlier_pct: null
min_em_backbone_inclusion: 0.7     # drop cryo-EM entries whose backbone is poorly in-density
require_validation_report: false

ligand_context_radius_A: 8.0
max_ligand_atoms: 25
'''

# recipe name (an ``if-split init --recipe`` choice) -> embedded YAML text.
RECIPES: dict[str, str] = {
    "default": RECIPE_DEFAULT,
    "fold-aware": RECIPE_FOLD_AWARE,
}
