"""Stage 2 orchestration: turn a built manifest into a hydrated, ML-ready dataset.

Ties together split selection, the structure fetcher, the dual index
(JSONL + optional Parquet), a copy of the manifest, and a generated dataset card.
Kept separate from ``download.py`` (the transport layer) so the I/O policy and
the MLOps packaging are easy to read and test independently.
"""

from __future__ import annotations

import json
from collections.abc import Callable
from pathlib import Path
from typing import Any

from . import __version__
from .download import SPLITS, StructureFetcher
from .manifest import (
    CLASSES_FILENAME,
    CLUSTERS_FILENAME,
    SPLIT_FILES,
    TARGETS_FILENAME,
    TIERS_FILENAME,
    read_classes,
    read_clusters,
    read_id_list,
    read_manifest,
    read_targets,
    read_tiers,
)

ProgressFn = Callable[[str], None]


def select_targets(
    manifest: dict[str, Any], splits: list[str], base_dir: Path | None = None
) -> list[tuple[str, str]]:
    """(entry_id, split) pairs for the requested splits, deterministically ordered.

    Reads each split's id list from its file (train.json etc.) next to the
    manifest. ``base_dir`` defaults to the manifest's directory.
    """
    base = Path(base_dir) if base_dir is not None else Path(".")
    split_files = manifest.get("files", {}).get("splits", SPLIT_FILES)
    targets: list[tuple[str, str]] = []
    for split in splits:
        fname = split_files.get(split, f"{split}.json")
        for eid in sorted(read_id_list(base / fname)):
            targets.append((eid, split))
    return targets


def _index_rows(
    fetch_rows: list[dict],
    classes: dict[str, list[str]],
    entry_clusters: dict[str, str],
    tiers: dict[str, dict] | None = None,
    targets: dict[str, list[str]] | None = None,
) -> list[dict]:
    """Enrich each fetched file with split metadata for the ML index.

    ``conditioning_targets`` is the list of functional-tier ligand comp ids the
    featurizer should condition on for this structure (``"nucleic_acid"`` for a
    protein/NA complex); empty means a backbone-only example.
    """
    tiers = tiers or {}
    targets = targets or {}
    rows: list[dict] = []
    for r in fetch_rows:
        eid = r["entry_id"]
        rows.append(
            {
                "entry_id": eid,
                "split": r["split"],
                "path": r["path"],
                "sha256": r["sha256"],
                "cluster": entry_clusters.get(eid),
                "ligand_classes": classes.get(eid, []),
                "ligand_tiers": tiers.get(eid, {}),
                "conditioning_targets": targets.get(eid, []),
            }
        )
    rows.sort(key=lambda r: (r["split"], r["entry_id"]))
    return rows


def write_index(rows: list[dict], root: Path) -> dict[str, Path]:
    """Write index.jsonl (always) and index.parquet (if pyarrow present)."""
    out: dict[str, Path] = {}
    jsonl = root / "index.jsonl"
    with jsonl.open("w", encoding="utf-8") as fh:
        for r in rows:
            fh.write(json.dumps(r, sort_keys=True, separators=(",", ":")) + "\n")
    out["jsonl"] = jsonl

    try:
        import pyarrow as pa
        import pyarrow.parquet as pq
    except ImportError:
        return out

    # Stringify nested fields for a clean, portable columnar schema.
    table = pa.table(
        {
            "entry_id": [r["entry_id"] for r in rows],
            "split": [r["split"] for r in rows],
            "path": [r["path"] for r in rows],
            "sha256": [r["sha256"] for r in rows],
            "cluster": [r["cluster"] for r in rows],
            "ligand_classes": [",".join(r["ligand_classes"]) for r in rows],
            "ligand_tiers_json": [json.dumps(r["ligand_tiers"], sort_keys=True) for r in rows],
        }
    )
    parquet = root / "index.parquet"
    pq.write_table(table, parquet)
    out["parquet"] = parquet
    return out


def _dataset_card(manifest: dict[str, Any], rows: list[dict], *, assembly: bool) -> str:
    counts = {s: sum(1 for r in rows if r["split"] == s) for s in SPLITS}
    cfg = manifest.get("config", {})
    unit = "biological assembly 1" if assembly else "asymmetric unit"
    cl = manifest["clustering"]
    clustering = f"{cl['backend']} @ {cl['identity']}% identity"
    return f"""# {manifest["dataset_version"]} — structures

Generated by IF-Split {__version__}. Coordinates fetched from RCSB
({unit}, gzipped mmCIF). Reproducible from the source split.

## Provenance
- **config hash:** `{manifest["config_hash"]}`
- **snapshot date:** `{cfg.get("snapshot_date", "?")}` (entries with release_date <= this)
- **clustering:** {clustering}
- **candidates.sha256:** `{manifest["candidates"]["sha256"]}`

## Splits (hydrated)
| split | structures |
|-------|-----------:|
| train | {counts["train"]:>10,} |
| val   | {counts["val"]:>10,} |
| test  | {counts["test"]:>10,} |

## Layout
```
structures/<split>/<shard>/<id>{"-assembly1" if assembly else ""}.cif.gz
```
`<shard>` is the PDB "divided" scheme — the middle two characters of the entry id
(e.g. `4hhb` -> `hh/`) — so no single split directory holds an unwieldy number of
files. Browsable by hand, scalable to the whole PDB.

## Files
- `index.jsonl` / `index.parquet` — one row per structure: entry_id, split, path,
  sha256, cluster, ligand_classes, ligand_tiers. The `sha256` lets you verify
  integrity and de-duplicate; `cluster` lets you sample cluster-balanced batches.
- `manifest.json` — the full source split manifest (config, drop log, per-class
  counts, component stats).

## Load (Python)
```python
import pandas as pd
df = pd.read_parquet("index.parquet")          # or pd.read_json("index.jsonl", lines=True)
train = df[df.split == "train"]
# one representative per cluster (de-redundified):
epoch = train.sort_values("entry_id").groupby("cluster").head(1)
```

## Integrity
Every structure's sha256 is recorded in `index.jsonl`. Re-verify the whole tree:
```bash
python - <<'PY'
import hashlib, json
from pathlib import Path
bad = [r["entry_id"] for r in map(json.loads, open("index.jsonl"))
       if hashlib.sha256(Path(r["path"]).read_bytes()).hexdigest() != r["sha256"]]
print("OK" if not bad else "MISMATCH: " + ", ".join(bad))
PY
```
Re-running `fetch` is resumable and re-checks existing files against these hashes.
"""


def hydrate(
    manifest_path: str | Path,
    root: str | Path,
    *,
    splits: list[str] | None = None,
    assembly: bool = True,
    workers: int = 8,
    fetcher: StructureFetcher | None = None,
    progress: ProgressFn | None = None,
) -> dict[str, Any]:
    """Download structures for a manifest and write the ML-ready package.

    Returns a summary dict. Idempotent: re-running skips files already present.
    """
    manifest = read_manifest(manifest_path)
    src = Path(manifest_path).parent
    files = manifest.get("files", {})
    # Split membership + supporting maps live in sidecar files next to the manifest.
    classes = read_classes(src / files.get("ligand_classes", CLASSES_FILENAME))
    entry_clusters = read_clusters(src / files.get("clusters", CLUSTERS_FILENAME))
    tiers = read_tiers(src / files.get("ligand_tiers", TIERS_FILENAME))
    # entry -> functional conditioning-target comp ids (nucleic_acid uses that literal).
    target_comps: dict[str, list[str]] = {}
    for t in read_targets(src / files.get("targets", TARGETS_FILENAME)):
        if t.get("tier") == "functional":
            target_comps.setdefault(t["entry_id"], []).append(t.get("comp_id") or t["class"])
    root = Path(root)
    root.mkdir(parents=True, exist_ok=True)
    splits = splits or list(SPLITS)

    targets = select_targets(manifest, splits, base_dir=src)

    owns = fetcher is None
    fetcher = fetcher or StructureFetcher(assembly=assembly, workers=workers)
    try:
        res = fetcher.fetch(targets, root, progress=progress)
    finally:
        if owns:
            fetcher.close()

    rows = _index_rows(res.index_rows, classes, entry_clusters, tiers, target_comps)
    index_paths = write_index(rows, root)
    (root / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    (root / "DATASET_CARD.md").write_text(
        _dataset_card(manifest, rows, assembly=assembly), encoding="utf-8"
    )

    return {
        "root": str(root),
        "requested": len(targets),
        "fetched": len(res.fetched),
        "skipped": len(res.skipped),
        "failed": res.failed,
        "index": {k: str(v) for k, v in index_paths.items()},
    }
